### PR TITLE
ported to PyQt6

### PR DESCRIPTION
**Pull request by trel**
Mac M1 still having trouble with PyQt5.

### CODE REVIEW

**Comment by Andries-B** [comment]
Tested on linux and windows: OK.

**Review by Andries-B — APPROVED** [review]

**Comment by Andries-B** [comment]
all OK, squkash and merge

**Comment by trel** [comment]
i will squash and force-push back to this branch/PR.   can you re-open it?

**Comment by Andries-B** [comment]
sorry for being so illiterate with github, trying to re-open but cannot find the button (using the web client)

**Comment by trel** [comment]
no worries - new PR coming :)

**Pull request closed without merging**
